[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.dependencies]
# wasmtime = { version = "=39.0.1", features = ["component-model-async"] }
wasmtime = { version = "=40.0.0", features = ["component-model-async"] }

wit-bindgen = "=0.50.0"
wit-component = "=0.243.0"
